<?php

declare(strict_types=1);

/**
 * This file is part of the PHP-Pohoda-Connector package
 *
 * https://github.com/VitexSoftware/PHP-Pohoda-Connector
 *
 * (c) VitexSoftware. <https://vitexsoftware.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\mServer;

use mServer\Addressbook;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-01-01 at 21:47:12.
 *
 * @no-named-arguments
 */
class AddressbookTest extends \PHPUnit\Framework\TestCase
{
    public static $addressBookRecord = [
        'identity' => [// Základní údaje
            'address' => [// Adresa.
                'company' => 'Vitex Software',
                'name' => 'Vítězslav Dvořák',
                'city' => 'Prague',
                'street' => 'Long',
                'zip' => '15800',
                'ico' => '69438676',
                'dic' => 'CZ7808072811',
            ],
        ],
        'mobil' => '739778202', // Mobil.
        'note' => 'note', // Poznámka.
        'p2' => 'true', // Klíč P2 / Odběratel.
        'web' => 'https://www.vitexsoftware.cz', // Adresa www stránek.
    ];
    protected Addressbook $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Addressbook(self::$addressBookRecord);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \mServer\Adressbook::create
     */
    public function testCreate(): void
    {
        $result = $this->object->create(self::$addressBookRecord);
        $this->assertIsInt($result, 'create() should return an integer');
        $this->assertEquals(1, $result, 'create() should return 1 on success');
    }

    /**
     * @covers \mServer\Addressbook::addToPohoda
     */
    public function testAddToPohoda(): void
    {
        $result = $this->object->addToPohoda();
        $this->assertTrue(\is_int($result) || $result instanceof Addressbook, 'addToPohoda() should return an integer or Addressbook instance');
    }

    /**
     * @covers \mServer\Adressbook::commit
     */
    public function testCommit(): void
    {
        $this->object->addToPohoda();
        $result = $this->object->commit();
        $this->assertTrue($result === true || $result === 1 || $result === false, 'commit() should return true, 1, or false');
    }

    /**
     * @covers \mServer\Adressbook::getResponse
     */
    public function testGetResponse(): void
    {
        $this->object->addToPohoda();
        $this->object->commit();
        $response = $this->object->response;
        $this->assertNotNull($response, 'Response should not be null after commit');

        if ($response !== null) {
            $this->assertTrue(property_exists($response, 'producedDetails'), 'Response should have producedDetails property');
        }
    }

    /**
     * @covers \mServer\Addressbook::updateInPohoda
     */
    public function testUpdateInPohoda()
    {
        $this->object->addToPohoda();
        $this->object->commit();
        $this->assertTrue($this->object->response->isOk() || $this->object->response->isWarning(), 'Create failed: '.print_r($this->object->response->messages, true));
    }
}
