<?php

declare(strict_types=1);

/**
 * This file is part of the PHP-Pohoda-Connector package
 *
 * https://github.com/VitexSoftware/PHP-Pohoda-Connector
 *
 * (c) VitexSoftware. <https://vitexsoftware.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\mServer;

use mServer\Bank;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-05-12 at 09:10:57.
 */
class BankTest extends \PHPUnit\Framework\TestCase
{
    protected Bank $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Bank();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \mServer\Bank::create
     *
     * @todo   Implement testcreate().
     */
    public function testcreate(): void
    {
        $this->assertEquals('', $this->object->create());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Bank::takeData
     *
     * @todo   Implement testtakeData().
     */
    public function testtakeData(): void
    {
        $this->assertEquals('', $this->object->takeData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Bank::setObjectName
     *
     * @todo   Implement testsetObjectName().
     */
    public function testsetObjectName(): void
    {
        $this->assertEquals('', $this->object->setObjectName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Bank::addSummary
     *
     * @todo   Implement testaddSummary().
     */
    public function testaddSummary(): void
    {
        $this->assertEquals('', $this->object->addSummary());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Bank::getFromPohoda
     *
     * @todo   Implement testgetFromPohoda().
     */
    public function testgetFromPohoda(): void
    {
        $this->assertEquals('', $this->object->getFromPohoda());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Bank::populate
     *
     * @todo   Implement testpopulate().
     */
    public function testpopulate(): void
    {
        $this->assertEquals('', $this->object->populate());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
