<?php

namespace Test\mServer;

use mServer\Invoice;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-01-01 at 21:47:41.
 */
class InvoiceTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Invoice
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Invoice();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers mServer\Invoice::create
     * @todo   Implement testcreate().
     */
    public function testcreate() {
        $this->assertEquals('', $this->object->create());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers mServer\Invoice::addItem
     * @todo   Implement testaddItem().
     */
    public function testaddItem() {
        $this->assertEquals('', $this->object->addItem());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers mServer\Invoice::extId
     * @todo   Implement testextId().
     */
    public function testextId() {
        $this->assertEquals('', $this->object->extId());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
