<?php

declare(strict_types=1);

/**
 * This file is part of the PHP-Pohoda-Connector package
 *
 * https://github.com/VitexSoftware/PHP-Pohoda-Connector
 *
 * (c) VitexSoftware. <https://vitexsoftware.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\mServer;

use mServer\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-01-01 at 21:47:42.
 */
class ResponseTest extends \PHPUnit\Framework\TestCase
{
    protected Response $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Response();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \mServer\Response::useCaller
     *
     * @todo   Implement testuseCaller().
     */
    public function testuseCaller(): void
    {
        $this->assertEquals('', $this->object->useCaller());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::processResponsePack
     *
     * @todo   Implement testprocessResponsePack().
     */
    public function testprocessResponsePack(): void
    {
        $this->assertEquals('', $this->object->processResponsePack());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::processResponsePackItem
     *
     * @todo   Implement testprocessResponsePackItem().
     */
    public function testprocessResponsePackItem(): void
    {
        $this->assertEquals('', $this->object->processResponsePackItem());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::processProducedDetails
     *
     * @todo   Implement testprocessProducedDetails().
     */
    public function testprocessProducedDetails(): void
    {
        $this->assertEquals('', $this->object->processProducedDetails());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::processImportDetails
     *
     * @todo   Implement testprocessImportDetails().
     */
    public function testprocessImportDetails(): void
    {
        $this->assertEquals('', $this->object->processImportDetails());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::processResponseData
     *
     * @todo   Implement testprocessResponseData().
     */
    public function testprocessResponseData(): void
    {
        $this->assertEquals('', $this->object->processResponseData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::typesToArray
     *
     * @todo   Implement testtypesToArray().
     */
    public function testtypesToArray(): void
    {
        $this->assertEquals('', $this->object->typesToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::typeToArray
     *
     * @todo   Implement testtypeToArray().
     */
    public function testtypeToArray(): void
    {
        $this->assertEquals('', $this->object->typeToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::getNote
     *
     * @todo   Implement testgetNote().
     */
    public function testgetNote(): void
    {
        $this->assertEquals('', $this->object->getNote());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::isOk
     *
     * @todo   Implement testisOk().
     */
    public function testisOk(): void
    {
        $this->assertEquals('', $this->object->isOk());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::getState
     *
     * @todo   Implement testgetState().
     */
    public function testgetState(): void
    {
        $this->assertEquals('', $this->object->getState());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::getAgendaData
     *
     * @todo   Implement testgetAgendaData().
     */
    public function testgetAgendaData(): void
    {
        $this->assertEquals('', $this->object->getAgendaData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::prepareElement
     *
     * @todo   Implement testprepareElement().
     */
    public function testprepareElement(): void
    {
        $this->assertEquals('', $this->object->prepareElement());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::anyXmlToArray
     *
     * @todo   Implement testanyXmlToArray().
     */
    public function testanyXmlToArray(): void
    {
        $this->assertEquals('', $this->object->anyXmlToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::parse
     *
     * @todo   Implement testparse().
     */
    public function testparse(): void
    {
        $this->assertEquals('', $this->object->parse());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \mServer\Response::xmlToArray
     *
     * @todo   Implement testxmlToArray().
     */
    public function testxmlToArray(): void
    {
        $this->assertEquals('', $this->object->xmlToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
