Pohoda\Isdoc\IsdocSettingsType:
    properties:
        fileName:
            expose: true
            access_type: public_method
            serialized_name: fileName
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
            accessor:
                getter: getFileName
                setter: setFileName
            type: string
        versionIsdocDocument:
            expose: true
            access_type: public_method
            serialized_name: versionIsdocDocument
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
            accessor:
                getter: getVersionIsdocDocument
                setter: setVersionIsdocDocument
            type: string
        signatureCertificate:
            expose: true
            access_type: public_method
            serialized_name: signatureCertificate
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
            accessor:
                getter: getSignatureCertificate
                setter: setSignatureCertificate
            type: Pohoda\Isdoc\SignatureCertificateType
        secureHashAlgorithm:
            expose: true
            access_type: public_method
            serialized_name: secureHashAlgorithm
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
            accessor:
                getter: getSecureHashAlgorithm
                setter: setSecureHashAlgorithm
            type: Pohoda\Isdoc\SecureHashAlgorithmType
        identificationOfStockitem:
            expose: true
            access_type: public_method
            serialized_name: identificationOfStockitem
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
            accessor:
                getter: getIdentificationOfStockitem
                setter: setIdentificationOfStockitem
            type: string
        attachments:
            expose: true
            access_type: public_method
            serialized_name: attachments
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
            accessor:
                getter: getAttachments
                setter: setAttachments
            type: array<Pohoda\Isdoc\AttachmentType>
            xml_list:
                inline: false
                entry_name: attachment
                skip_when_empty: true
                namespace: 'http://www.stormware.cz/schema/version_2/isdoc.xsd'
