Pohoda\Prodejka\ProdejkaItemType:
    properties:
        link:
            expose: true
            access_type: public_method
            serialized_name: link
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getLink
                setter: setLink
            type: Pohoda\Type\LinkItemType
        linkedDocument:
            expose: true
            access_type: public_method
            serialized_name: linkedDocument
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getLinkedDocument
                setter: setLinkedDocument
            type: Pohoda\Type\LinkedDocumentType
        refundItem:
            expose: true
            access_type: public_method
            serialized_name: refundItem
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getRefundItem
                setter: setRefundItem
            type: Pohoda\Type\SourceDocumentItemType
        id:
            expose: true
            access_type: public_method
            serialized_name: id
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getId
                setter: setId
            type: int
        extId:
            expose: true
            access_type: public_method
            serialized_name: extId
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getExtId
                setter: setExtId
            type: string
        text:
            expose: true
            access_type: public_method
            serialized_name: text
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getText
                setter: setText
            type: string
        quantity:
            expose: true
            access_type: public_method
            serialized_name: quantity
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getQuantity
                setter: setQuantity
            type: float
        unit:
            expose: true
            access_type: public_method
            serialized_name: unit
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getUnit
                setter: setUnit
            type: string
        coefficient:
            expose: true
            access_type: public_method
            serialized_name: coefficient
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getCoefficient
                setter: setCoefficient
            type: float
        payVAT:
            expose: true
            access_type: public_method
            serialized_name: payVAT
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getPayVAT
                setter: setPayVAT
            type: string
        rateVAT:
            expose: true
            access_type: public_method
            serialized_name: rateVAT
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getRateVAT
                setter: setRateVAT
            type: Pohoda\Type\VatRateType
        percentVAT:
            expose: true
            access_type: public_method
            serialized_name: percentVAT
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getPercentVAT
                setter: setPercentVAT
            type: float
        discountPercentage:
            expose: true
            access_type: public_method
            serialized_name: discountPercentage
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getDiscountPercentage
                setter: setDiscountPercentage
            type: float
        homeCurrency:
            expose: true
            access_type: public_method
            serialized_name: homeCurrency
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getHomeCurrency
                setter: setHomeCurrency
            type: Pohoda\Type\TypeCurrencyHomeItemType
        recyclingContrib:
            expose: true
            access_type: public_method
            serialized_name: recyclingContrib
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getRecyclingContrib
                setter: setRecyclingContrib
            type: Pohoda\Type\RecyclingContribType
        note:
            expose: true
            access_type: public_method
            serialized_name: note
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getNote
                setter: setNote
            type: string
        code:
            expose: true
            access_type: public_method
            serialized_name: code
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getCode
                setter: setCode
            type: string
        guarantee:
            expose: true
            access_type: public_method
            serialized_name: guarantee
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getGuarantee
                setter: setGuarantee
            type: int
        guaranteeType:
            expose: true
            access_type: public_method
            serialized_name: guaranteeType
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getGuaranteeType
                setter: setGuaranteeType
            type: string
        stockItem:
            expose: true
            access_type: public_method
            serialized_name: stockItem
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getStockItem
                setter: setStockItem
            type: Pohoda\Type\StockItemType
        accounting:
            expose: true
            access_type: public_method
            serialized_name: accounting
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getAccounting
                setter: setAccounting
            type: Pohoda\Type\RefType
        centre:
            expose: true
            access_type: public_method
            serialized_name: centre
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getCentre
                setter: setCentre
            type: Pohoda\Type\RefType
        activity:
            expose: true
            access_type: public_method
            serialized_name: activity
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getActivity
                setter: setActivity
            type: Pohoda\Type\RefType
        contract:
            expose: true
            access_type: public_method
            serialized_name: contract
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getContract
                setter: setContract
            type: Pohoda\Type\RefType
        expirationDate:
            expose: true
            access_type: public_method
            serialized_name: expirationDate
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getExpirationDate
                setter: setExpirationDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        eETItem:
            expose: true
            access_type: public_method
            serialized_name: EETItem
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getEETItem
                setter: setEETItem
            type: string
        eKasaItem:
            expose: true
            access_type: public_method
            serialized_name: eKasaItem
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getEKasaItem
                setter: setEKasaItem
            type: Pohoda\Prodejka\EKasaItemType
        parameters:
            expose: true
            access_type: public_method
            serialized_name: parameters
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getParameters
                setter: setParameters
            type: array<Pohoda\Type\ParameterDocType>
            xml_list:
                inline: false
                entry_name: parameter
                skip_when_empty: true
                namespace: 'http://www.stormware.cz/schema/version_2/type.xsd'
