Pohoda\Prodejka\ProdejkaHeaderType:
    properties:
        id:
            expose: true
            access_type: public_method
            serialized_name: id
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getId
                setter: setId
            type: int
        extId:
            expose: true
            access_type: public_method
            serialized_name: extId
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getExtId
                setter: setExtId
            type: Pohoda\Type\ExtIdType
        prodejkaType:
            expose: true
            access_type: public_method
            serialized_name: prodejkaType
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getProdejkaType
                setter: setProdejkaType
            type: string
        storno:
            expose: true
            access_type: public_method
            serialized_name: storno
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getStorno
                setter: setStorno
            type: string
        number:
            expose: true
            access_type: public_method
            serialized_name: number
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getNumber
                setter: setNumber
            type: Pohoda\Type\NumberType
        date:
            expose: true
            access_type: public_method
            serialized_name: date
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getDate
                setter: setDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        accounting:
            expose: true
            access_type: public_method
            serialized_name: accounting
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getAccounting
                setter: setAccounting
            type: Pohoda\Type\AccountingType
        text:
            expose: true
            access_type: public_method
            serialized_name: text
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getText
                setter: setText
            type: string
        partnerIdentity:
            expose: true
            access_type: public_method
            serialized_name: partnerIdentity
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getPartnerIdentity
                setter: setPartnerIdentity
            type: Pohoda\Type\AddressType
        paymentType:
            expose: true
            access_type: public_method
            serialized_name: paymentType
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getPaymentType
                setter: setPaymentType
            type: Pohoda\Type\PaymentType
        priceLevel:
            expose: true
            access_type: public_method
            serialized_name: priceLevel
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getPriceLevel
                setter: setPriceLevel
            type: Pohoda\Type\RefType
        centre:
            expose: true
            access_type: public_method
            serialized_name: centre
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getCentre
                setter: setCentre
            type: Pohoda\Type\RefType
        activity:
            expose: true
            access_type: public_method
            serialized_name: activity
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getActivity
                setter: setActivity
            type: Pohoda\Type\RefType
        contract:
            expose: true
            access_type: public_method
            serialized_name: contract
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getContract
                setter: setContract
            type: Pohoda\Type\RefType
        kasa:
            expose: true
            access_type: public_method
            serialized_name: kasa
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getKasa
                setter: setKasa
            type: Pohoda\Type\RefType
        note:
            expose: true
            access_type: public_method
            serialized_name: note
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getNote
                setter: setNote
            type: string
        intNote:
            expose: true
            access_type: public_method
            serialized_name: intNote
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getIntNote
                setter: setIntNote
            type: string
        histRate:
            expose: true
            access_type: public_method
            serialized_name: histRate
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getHistRate
                setter: setHistRate
            type: string
        lock1:
            expose: true
            access_type: public_method
            serialized_name: lock1
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getLock1
                setter: setLock1
            type: string
        lock2:
            expose: true
            access_type: public_method
            serialized_name: lock2
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getLock2
                setter: setLock2
            type: string
        markRecord:
            expose: true
            access_type: public_method
            serialized_name: markRecord
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getMarkRecord
                setter: setMarkRecord
            type: string
        labels:
            expose: true
            access_type: public_method
            serialized_name: labels
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getLabels
                setter: setLabels
            type: array<Pohoda\Type\LabelType>
            xml_list:
                inline: false
                entry_name: label
                skip_when_empty: true
                namespace: 'http://www.stormware.cz/schema/version_2/type.xsd'
        parameters:
            expose: true
            access_type: public_method
            serialized_name: parameters
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getParameters
                setter: setParameters
            type: array<Pohoda\Type\ParameterDocType>
            xml_list:
                inline: false
                entry_name: parameter
                skip_when_empty: true
                namespace: 'http://www.stormware.cz/schema/version_2/type.xsd'
        validate:
            expose: true
            access_type: public_method
            serialized_name: validate
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getValidate
                setter: setValidate
            type: Pohoda\Type\TypeValidateType
