Pohoda\Prodejka\ProdejkaSummaryType:
    properties:
        roundingDocument:
            expose: true
            access_type: public_method
            serialized_name: roundingDocument
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getRoundingDocument
                setter: setRoundingDocument
            type: string
        roundingVAT:
            expose: true
            access_type: public_method
            serialized_name: roundingVAT
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getRoundingVAT
                setter: setRoundingVAT
            type: string
        calculateVAT:
            expose: true
            access_type: public_method
            serialized_name: calculateVAT
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getCalculateVAT
                setter: setCalculateVAT
            type: bool
        typeCalculateVATInclusivePrice:
            expose: true
            access_type: public_method
            serialized_name: typeCalculateVATInclusivePrice
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getTypeCalculateVATInclusivePrice
                setter: setTypeCalculateVATInclusivePrice
            type: string
        homeCurrency:
            expose: true
            access_type: public_method
            serialized_name: homeCurrency
            xml_element:
                namespace: 'http://www.stormware.cz/schema/version_2/prodejka.xsd'
            accessor:
                getter: getHomeCurrency
                setter: setHomeCurrency
            type: Pohoda\Type\TypeCurrencyHomeType
